/** Data point for time-series charts. */
export interface DataPoint {
  date: string;
  value: number;
}

/** Series data fetched from an API source. */
export interface SeriesData {
  series_id?: string;
  source?: string;
  frequency?: string;
  values: DataPoint[];
}

/** Highlight range for annotating chart regions (e.g., recessions). */
export interface HighlightRange {
  start: string;
  end: string;
  label: string;
  color: string;
}

/** Props for the TitleCard component. */
export interface TitleCardProps {
  title: string;
  accent_color?: string;
}

/** Props for the FactHighlight component. */
export interface FactHighlightProps {
  value: string;
  label: string;
  unit?: string;
  accent_color?: string;
}

/** Word-level timestamp from STT. */
export interface WordTimestamp {
  word: string;
  start: number;
  end: number;
}

/** Props for the NarrationSubtitle component. */
export interface NarrationSubtitleProps {
  word_timestamps: WordTimestamp[];
}

/** Props for the InfoCard component. */
export interface InfoCardProps {
  text: string;
  background_color?: string;
  text_box_color?: string;
  illustration_url?: string;
  layout?: "image-left" | "image-right";
  show_particles?: boolean;
  accent_color?: string;
}

/** Props for the InfoSlide component. */
export interface InfoSlideProps {
  text: string;
  title?: string;
  illustration_url?: string;
  layout?: "image-left" | "image-right";
  background_color?: string;
  background_tint_color?: string;
  title_color?: string;
  body_color?: string;
  accent_color?: string;
  highlighted_keywords?: string[];
  highlight_color?: string;
}

/** Props for the TextOnlySlide component. */
export interface TextOnlySlideProps {
  text: string;
  title?: string;
  variant?: "ai_prompt_preview";
  model?: string;
  operation?: string;
  prompt_text?: string;
  background_color?: string;
  background_tint_color?: string;
  title_color?: string;
  body_color?: string;
  accent_color?: string;
  highlighted_keywords?: string[];
  highlight_color?: string;
}

/** Props for the ImageScene component. */
export interface ImageSceneProps {
  image_path: string;
  animation_preset?: "parallax" | "drift" | "zoom_focus";
  direction?: "left" | "right" | "up" | "down";
}

/** Single bar in an AnimatedBarChart. */
export interface BarItem {
  label: string;
  value: number;
}

/** Single item in a ComparisonBars chart. */
export interface ComparisonItem {
  label: string;
  value: number;
}

/** Scene descriptor as generated by the AI script stage. */
export interface SceneDescriptor {
  component: string;
  data_query?: {
    source: string;
    series_id: string;
    start_date?: string;
    end_date?: string;
    frequency?: string;
    transform?: string;
  };
  layout: Record<string, unknown>;
  style: Record<string, unknown>;
  images_needed?: boolean;
}
